version: 0.2

env:
  variables:
    PACKER_VERSION: '1.3.3'

phases:
  pre_build:
    commands:
      - echo "Installing Packer..."
      - curl -o packer.zip https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip && unzip packer.zip
      - echo "Validating Packer template..."
      - ./packer validate ubuntu-packer-template.json
      - echo "Pre-build complete."

  build:
    commands:
      - ./packer build -color=false ubuntu-packer-template.json
